trigger:
  - main
pool:  
  vmImage: 
    'windows-2019'
steps:
  - task: UseNode@1  
    inputs:    
      version: '18.x'  
    displayName: 'Install Node.js'
  - script: |    
      npm install  
    displayName: 'npm install'
  - script: |    
      npm run build  
    displayName: 'npm build'

  - task: CopyFiles@2
    inputs:
      sourceFolder: 'dist/frontend/browser'
      targetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy project files'

  - task: PublishPipelineArtifact@1
    inputs:
      artifactName: app
      targetPath: '$(Build.ArtifactStagingDirectory)'
      publishLocation: 'pipeline'
    displayName: 'Publish npm artifact'